// <auto-generated />
namespace RentC.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddClients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClients));
        
        string IMigrationMetadata.Id
        {
            get { return "202001191714445_AddClients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
